### ISSUE TITLE
Add Dockerfile and docker-compose for grobid and project

### ISSUE THREAD

**Issue by jpwahle** [gipplab/cs-insights-crawler#80]
**Is your feature request related to a problem? Please describe.**
[Grobid](https://github.com/kermitt2/grobid) requires us to run a server for processing.

**Describe the solution you'd like**
Add a Dockerfile that builds the current project and a docker-compose.yml that connects both the project and grobid.

**Comment by jpelhaW** [comment]
Also add a push to dockerhub for the release stage so that the crawler is available to the dke01 server.
